### ISSUE TITLE
Component error: tibber_custom - Integration 'tibber_custom' not found.

### ISSUE THREAD

**Issue by mikaelbrems** [Danielhiversen/home_assistant_tibber_custom#10]
Assuming this custom repository should be added as an integration in HACS? Selecting any other category gives error "Repostitory structure for 0.2 is not compliant"

After adding "tibber_custom:" to configuration.yaml I get errors in log when restarting HA:

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:420
Integration: Hass.io (documentation, issues)
First occurred: 10:02:40 (1 occurrences)
Last logged: 10:02:40

Component error: tibber_custom - Integration 'tibber_custom' not found.

There are also two other errors showing up in log that probably is related (they dissapear when "tibber_custom:" is not present in configuration.yaml);

Logger: root
Source: helpers/entity.py:422
First occurred: 10:02:34 (20 occurrences)
Last logged: 10:11:34

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 181, in update_status_information
    self.raise_updated()
  File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 36, in raise_updated
    callback(self)
  File "/config/custom_components/shelly/block.py", line 68, in _updated
    self._update_ha_state()
  File "/config/custom_components/shelly/block.py", line 60, in _update_ha_state
    self.schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 422, in schedule_update_ha_state
    assert self.hass is not None
AssertionError

Logger: pyShelly
Source: helpers/entity.py:422
First occurred: 10:02:34 (16 occurrences)
Last logged: 10:11:34

Error update device status: 227F90 SHSW-1, , Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 191, in update_status_information dev.raise_updated(force_update_devices) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 36, in raise_updated callback(self) File "/config/custom_components/shelly/device.py", line 59, in _updated self._update_ha_state() File "/config/custom_components/shelly/device.py", line 51, in _update_ha_state self.schedule_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 422, in schedule_update_ha_state assert self.hass is not None AssertionError
Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 191, in update_status_information
    dev.raise_updated(force_update_devices)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 36, in raise_updated
    callback(self)
  File "/config/custom_components/shelly/device.py", line 59, in _updated
    self._update_ha_state()
  File "/config/custom_components/shelly/device.py", line 51, in _update_ha_state
    self.schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 422, in schedule_update_ha_state
    assert self.hass is not None
AssertionError

Otherwise this seems as awesome stuff for HA and Tibber users :)

**Comment by Danielhiversen** [comment]
> Assuming this custom repository should be added as an integration in HACS? 

Yes
