### ISSUE TITLE
No Image generated

### ISSUE THREAD

**Issue by rypeveien** [Danielhiversen/home_assistant_tibber_custom#28]
this is from the log: 

2022-03-22 09:41:26 DEBUG (MainThread) [custom_components.tibber_custom.camera] Failed to generate image
Traceback (most recent call last):
  File "/config/custom_components/tibber_custom/camera.py", line 211, in _generate_fig
    await self.hass.async_add_executor_job(fig.savefig, self._path)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3019, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 412, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 540, in print_png
    FigureCanvasAgg.draw(self)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/figure.py", line 2810, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3046, in draw
    self._update_title_position(renderer)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 2986, in _update_title_position
    bb = ax.xaxis.get_tightbbox(renderer)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/axis.py", line 1103, in get_tightbbox
    ticks_to_draw = self._update_ticks()
  File "/usr/local/lib/python3.9/site-packages/matplotlib/axis.py", line 1045, in _update_ticks
    major_locs = self.get_majorticklocs()
  File "/usr/local/lib/python3.9/site-packages/matplotlib/axis.py", line 1277, in get_majorticklocs
    return self.major.locator()
  File "/usr/local/lib/python3.9/site-packages/matplotlib/dates.py", line 1340, in __call__
    dmin, dmax = self.viewlim_to_dt()
  File "/usr/local/lib/python3.9/site-packages/matplotlib/dates.py", line 1125, in viewlim_to_dt
    return num2date(vmin, self.tz), num2date(vmax, self.tz)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/dates.py", line 528, in num2date
    return _from_ordinalf_np_vectorized(x, tz).tolist()
  File "/usr/local/lib/python3.9/site-packages/numpy/lib/function_base.py", line 2163, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/usr/local/lib/python3.9/site-packages/numpy/lib/function_base.py", line 2246, in _vectorize_call
    outputs = ufunc(*inputs)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/dates.py", line 359, in _from_ordinalf
    dt = dt.astimezone(tz)
ValueError: fromutc: non-None dst() result required

**Comment by fajbzz** [comment]
## System Health

version | core-2022.2.9
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.0-6-amd64
arch | x86_64
timezone | Europe/Oslo

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Easee EV charger</summary>

component_version | 0.9.39
-- | --
reach_easee_cloud | ok
connected2stream | true

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 2
views | 5
mode | storage

</details>

**Comment by Danielhiversen** [comment]
Could you try to update to 0.5?
