### ISSUE TITLE
error message: Could not find currency 

### ISSUE THREAD

**Issue by terchris** [Danielhiversen/home_assistant_tibber_custom#44]
I get an error after installing the tibber_custom (log below) and I suspect that the reason for the error can be that I have signed up with tibber. But the switch from my previous supplier to tibber is not effective yet.

The following fields are missing (Unknown) from the data I get from tibber:
Monthly cost 1etg -> Unknown
Monthly net consumption 1etg ->Unknown
Monthly peak hour consumption 1etg ->Unknown
Time of max hour consumption 1etg ->Unknown

The log
```
2022-09-26 22:09:29.771 ERROR (MainThread) [tibber] Could not find currency.
2022-09-26 22:09:31.288 ERROR (MainThread) [tibber] Could not find currency.
2022-09-26 22:09:31.440 ERROR (MainThread) [homeassistant.components.sensor] tibber: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
await task
File "/usr/src/homeassistant/homeassistant/components/tibber/sensor.py", line 374, in async_update
self._attr_native_value, price_level, self._last_updated = res
TypeError: cannot unpack non-iterable NoneType object
2022-09-26 22:09:32.282 ERROR (MainThread) [homeassistant.components.sensor] tibber: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
await task
File "/usr/src/homeassistant/homeassistant/components/tibber/sensor.py", line 374, in async_update
self._attr_native_value, price_level, self._last_updated = res
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by Anden78** [comment]
This is an issue I have from the two resents updates in HA too. 
It worked but suddenly current price is not available.

**Comment by Danielhiversen** [comment]
Not related to this custom component
