### ISSUE TITLE
Detected blocking call to import_module inside the event loop by custom integration 'tibber_custo

### ISSUE THREAD

**Issue by LEJOUI** [Danielhiversen/home_assistant_tibber_custom#57]
Warning shown in logbook:

`Detected blocking call to import_module inside the event loop by custom integration 'tibber_custom' at custom_components/tibber_custom/camera.py, line 32: matplotlib.use("Agg") (offender: /usr/local/lib/python3.12/site-packages/matplotlib/backends/registry.py, line 316: return importlib.import_module(module_name)), please create a bug report at https://github.com/Danielhiversen/home_assistant_tibber_custom/issues`

**Comment by RedDaveNY** [comment]
Same problem here

Detected blocking call to import_module with args ('matplotlib.backends.backend_agg',) inside the event loop by custom integration 'tibber_custom' at custom_components/tibber_custom/camera.py, line 32: matplotlib.use("Agg") (offender: /usr/local/lib/python3.12/site-packages/matplotlib/backends/registry.py, line 323: return importlib.import_module(module_name)), please create a bug report at https://github.com/Danielhiversen/home_assistant_tibber_custom/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 164, in _async_component_platform_discovered await self.async_setup_platform(platform, {}, info) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 318, in async_setup_platform await self._platforms[key].async_setup(platform_config, discovery_info) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 301, in async_setup await self._async_setup_platform(async_create_setup_awaitable) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/config/custom_components/tibber_custom/camera.py", line 26, in async_setup_platform dev.append(TibberCam(home, hass)) File "/config/custom_components/tibber_custom/camera.py", line 32, in __init__ matplotlib.use("Agg")

**Comment by jove01** [comment]
same here

**Comment by typxxi** [comment]
what had you done regarding the matplotlib missing issue ?
